import { Inter } from "next/font/google";
import { HBOProvider } from "./components/Context/HboProvider";
import "./styles/main.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HBOmax clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        precedence="default"
        rel="preconnect"
        href="https://fonts.googleapis.com"
      />
      <link
        precedence="default"
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      <link
        precedence="default"
        href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap"
        rel="stylesheet"
      />
      <link
        precedence="default"
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      />
      <body className={inter.className}>
        <HBOProvider>{children}</HBOProvider>
      </body>
    </html>
  );
}
